# Generated by Django 5.2 on 2025-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlate', '0002_book_author_book_is_bestselling_alter_book_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_bestselling',
            field=models.BooleanField(default=False),
        ),
    ]
