# Generated by Django 5.2 on 2025-06-24 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlate', '0003_alter_book_is_bestselling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratting',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
