# Generated by Django 5.2 on 2025-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlate", "0006_remove_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
