# Generated by Django 5.2 on 2025-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlate", "0009_alter_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=20)),
            ],
        ),
    ]
