# Generated by Django 5.2 on 2025-06-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlate", "0010_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="adress",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_outlate.adress",
            ),
        ),
    ]
