# Generated by Django 5.2.3 on 2025-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlate", "0011_author_adress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("code", models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name="adress",
            options={"verbose_name_plural": "Address Entries"},
        ),
        migrations.AddField(
            model_name="book",
            name="published_country",
            field=models.ManyToManyField(to="book_outlate.country"),
        ),
    ]
